### ISSUE TITLE
Cosmostation crash when scanning QR code 

### ISSUE THREAD

**Issue by fgallaire** [cosmostation/cosmostation-mobile#110]
Setting -> Starname Wallet Connect -> Export Adress for Starname -> Continue
When I scan the QR code Cosmostation 1.5.3 crash with a beep.
Android 10

```
java.lang.IllegalStateException: Must be called from main thread of fragment host
 at android.app.FragmentManagerImpl.ensureExecReady(FragmentManager.java:2014)
 at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2066)
 at android.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:874)
 at android.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:835)
 at android.app.Activity.onBackPressed(Activity.java:3735)
 at androidx.activity.ComponentActivity.access$001(ComponentActivity.java:50)
 at androidx.activity.ComponentActivity$1.run(ComponentActivity.java:72)
 at androidx.activity.OnBackPressedDispatcher.onBackPressed(OnBackPressedDispatcher.java:194)
 at androidx.activity.ComponentActivity.onBackPressed(ComponentActivity.java:286)
 at wannabit.io.cosmostaion.activities.chains.starname.StarNameWalletConnectActivity$StarNameWcThread.run(StarNameWalletConnectActivity.java:231)
```

**Comment by fgallaire** [comment]
Always there in Cosmostation 1.5.4
